import type { Screen } from "./types";

export const screenOrder: Screen[] = [
  "login",
  "kakao",
  "permissionToast",
  "profile",
  "contacts",
  "contactModal",
  "terms",
  "permissionBasic",
  "callPermission",
  "permissionSos",
  "sosSystem",
  "complete",
  "home",
  "personaUse",
  "personaPeople",
  "callSetupCheck",
  "voiceLoading",
  "callRinging",
  "call",
  "help",
  "helpOpen",
  "setting",
  "settingDialog",
  "withdraw",
  "editProfile",
  "editContacts",
  "soundSetting",
  "permissionSetting",
];
